### ISSUE TITLE
Framework: after initial create of a framework and dialog still open, clicking the X brings up the Confirm Delete dialog

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1044]
Framework on staging
- Created a new framework
- After initial create of a framework and dialog still open, clicking the Done button would NOT close the dialog
- Then tried clicking the X 
- this brings up the Confirm Delete dialog

![image](https://user-images.githubusercontent.com/58825866/151722091-ca1bb90c-aba3-45cd-ae1f-c63242deea78.png)

**Comment by woodkri** [comment]
When you clicked done, were there errors such as publisherName not having a language (fix coming soon) or description required? Either would not allow the done button to close the dialog. With both filled in, I am able to click the done button and the modal closes.

The 'x' when you are first creating a new framework is seen as a cancellation of creating the framework, which is why that dialog comes up.

**Comment by mparsons-ce** [comment]
Yes, I didn't see the message regarding publisherName and language. 
I am not sure clicking the 'X' would normally be interpreted as a delete request.

**Comment by jeannekitchens** [comment]
Per @woodkri the X in the message needs to be removed.

**Comment by sedula27** [comment]
@woodkri  Tested the update and it works, we can move it to staging and production
