### ISSUE TITLE
Cannot Enter Competencies on Sandbox

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#1122]
I cannot enter any competencies on sandbox.  The message, "In Language is required. Please enter a value." keeps displaying regardless of it already being defaulted to en-us.  I tried selecting English from the dropdown as well.  I actually need it to be en-au (for english australia) don't see that option in the drop down and gives same error message.  Also, why is a field called "Value" showing?  
![image](https://user-images.githubusercontent.com/20917206/168934791-e8ebb572-0b43-40cc-be95-61d30fcb11ac.png)

**Comment by woodkri** [comment]
When I select English from the dropdown, it works for me. What do you see when you try it?

I noticed that the template postMessage is setting ceasn:inLanguage for both Framework and Competency; it should be schema:inLanguage to match how we store the language internally.

We try to fall back to another value for the language field, which is working for Frameworks but evidently not for Competencies. We're investigating why that is, but the postMessage fix should address this as well.

**Comment by jeannekitchens** [comment]
Kristin, 

I create a framework.
Select to create a competency and add it, rather than search for it.  It takes at least 4 seconds for the competency interface to come up. Yesterday it was really slow so I thought it wasn't adding the competency.

I add a competency and see the pop up below. You can see that it prefilled the language and that it has a field titled Value.  Value is not a CTDL property.  What is that?
![image](https://user-images.githubusercontent.com/20917206/169051820-aa57dec4-d297-4284-be3c-6bd11e3e200a.png)
I type in the competency and leave the default language and click Save and Add Another.  I keep getting the message below, In Language is required. Please enter a value. 
![image](https://user-images.githubusercontent.com/20917206/169052250-ea6d67b0-76b8-4017-a4d1-5b0353d802a2.png)
I click the X adjacent to language thinking it would clear it and let me enter a different language but get the message below.  The x should not show as active if it's not for clearing.
![image](https://user-images.githubusercontent.com/20917206/169052569-cba3bf6f-f2c3-4530-9d65-18cd9599b749.png)
Just now, I realized the value box below the competency is for the language even though it shows adjacent.
![image](https://user-images.githubusercontent.com/20917206/169052842-4c008193-2b7c-4770-b2ee-a4366d729298.png)
I click the red X adjacent to the inLanguage Value and get this message. The red x should not be active if the property cannot be removed.
![image](https://user-images.githubusercontent.com/20917206/169053030-79d093a1-b060-4282-b399-922d55efc324.png)
I choose another language, it leaves en-use adjacent to the competency adds in the abbreviation for the other language leaving me confused.  Why are there two language drop downs? 
![image](https://user-images.githubusercontent.com/20917206/169054153-d6cf5887-b67a-40ae-a331-fba68f85fad4.png)
So I can save the competency but the lnLanguage in two places in confusing, shouldn't have an active red X on the one that should remain.  I'm working with a group in Australia so not sure how to explain to them the en-us works but en-au doesn't work. en-au should be an option.

**Comment by woodkri** [comment]
The language is in two places because the ceasn:inLanguage property is being added back to competency. That property is distinct from the language that's associated with the competency text; a competency can have names in multiple languages but only one inLanguage (after we've addressed the multiplicity ticket).

The only dropdown option we have is "en"; the "en-US" value comes from the template being passed in or the default language associated with the user's browser. If you have an alternative list of codes you'd like for us to use in the dropdown please let me know. I used the only json list I was able to find, I think ours corresponds to this one that you have linked in the mapping sheet: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry.

I'll create a separate ticket for disabling the X on required properties, since that's a different issue.

**Comment by jeannekitchens** [comment]
Yes, to adding the inLanguage back to the Competency. I don't understand why a competency entered one in a language would have the language adjacent to it in the pop up and below it, and they might not match. I created a framework and identified the language for it so now I'm looking at a competency in a language.  The interface only allows one language per competency 
![image](https://user-images.githubusercontent.com/20917206/169065578-8a8eb445-c941-4c27-9ccc-f00fd8cd9635.png)

**Comment by woodkri** [comment]
We're working on getting the backup fixed for defaulting the inLanguage property. In the meantime, changing the template postmessage to use schema:inLanguage instead of ceasn:inLanguage would fix the mismatch.

The interface does only allow one competency text entry per language. It allows multiple entries if each has a different language associated though. The inLanguage property itself is currently multiple, but will be changing to a single value as we address the multiplicity ticket.

**Comment by jeannekitchens** [comment]
Thank you Kristin!
