### ISSUE TITLE
Outdenting a competency with keyboard commands not working

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#1129]
With a console message of Error: Retrieved object was not a https://schema.cassproject.org/0.4/Competency. Indenting, up and down appear to be working.

**Comment by gloverkari** [comment]
The remaining issue with keyboard controls appears to be with moving a competency to the last position of a framework. It turns out that this is not limited to keyboard shortcuts and will require a non-trivial fix, so I will open a new issue to cover it. 
The workaround is to select the competency in the last position and move up.

**Comment by sedula27** [comment]
can you give us the ticket number for the new issue, I don't see it on the Credential Engine Issue Tracking board
