### ISSUE TITLE
Need framework objects to be returned with selected competencies

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#119]
When you load in a JSON it pulls in the framework. Right now we deliver an object with a list of selected properties. We need the framework object to be returned along with a list of the competencies that are selected.

**Comment by kchavas** [comment]
This is also known as: 
When competencies are selected (or more specifically, when the "add" button is clicked), the data sent via postMessage needs to include data about the framework, not just the competencies ( https://github.com/CredentialEngine/CompetencyFrameworks/issues/46 )

**Comment by siuc-nate** [comment]
@Lomilar The schema for CTDL-ASN should be either "ctdl-asn" or "ctdlasn", or something along those lines. "ceasn" is a prefix used by the schema, but not a proper identifier for the schema itself.

**Comment by siuc-nate** [comment]
@Lomilar Would it be possible to return the framework object in the schema indicated by the URL parameter? Currently the framework object is returned in the CASS schema, meaning I have to do an export of the entire framework just to get the description, URL, etc., since I can only really get the name and `@id` from the CASS version.
