### ISSUE TITLE
Progression Model exports as type skos:ConceptScheme

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1209]
Progression Model type needs to be asn:ProgressionModel with Progression Levels of type asn:ProgressionLevel

**Comment by gloverkari** [comment]
Issue is in the ASN rdf.
It looks like there is a cut/paste error (ProficiencyScale is defined twice).


<rdfs:Class rdf:about="http://purl.org/ASN/schema/core/ProficiencyScale">
    <rdfs:label xml:lang="en-US">Proficiency Scale</rdfs:label>
    <rdfs:comment xml:lang="en-US">Model of identifiable points along a developmental progression including increasing levels of competence, achievement or temporal position (e.g., "Second Quarter").</rdfs:comment>
    <rdfs:isDefinedBy rdf:resource="http://purl.org/ASN/schema/core/"/>
</rdfs:Class>


From Jeanne (12/19/2022):
That file is created by Achievement Standards Network.  
[@Michael Parsons](https://eduworks.slack.com/team/URHA6SCD6)
 is emailing 
[@Stuart](https://eduworks.slack.com/team/UA41DKNDU)
 to see if he could possibly correct it.

**Comment by stuartasutton** [comment]
Gang, this error has been corrected. Please retrieve your files from here https://github.com/stuartasutton/asn instead of the ASN website. We have a number of updates that include correcting this problem that have not been deployed to the D2L website. Please note that you want the files with **Profile** in their name (asnProfile.rdf, asnProfile.jsonld) and asn.Context.jsonld if you are using the jsonld version as opposed to the rdf.

**Comment by gloverkari** [comment]
I'll update the link - thanks!

**Comment by gloverkari** [comment]
From Stuart:
I am in the process of making sure the asnProfile.rdf and asnProfile.jsonld are in sync at https://github.com/stuartasutton/asn. I should be finished with that work by mid-day tomorrow. It is very important that you use https://github.com/stuartasutton/asn github repo until Joseph has the updated files in place on the D2L server. I'll let you know when teh D2L versions should be referenced going forward.
