### ISSUE TITLE
Make URI errors user friendly, and put URI examples in tooltips.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#214]

**Comment by chinhseah** [comment]
Run with URL: /cass-editor/index.html?ceasnDataFields=true and create new Framework.

URI Examples will be:

Creator: http://example.com?t=idforFrameworkOwningorg
Publisher: http://example.com/?t=idforFrameworkPublishingorg
Webpage: http://example.com/?t=source
License: https://sandbox.credentialengineregistry.org/
Rights: http://example.com/?t=idforRights
Derived From: http://example.com/?t=derivedFrom
Rights Holder: http://example.com/?t=rightsHolder
 Identifier: https://sandbox.credentialengineregistry.org

**Comment by eddavies** [comment]
Feedback: 
The examples aren't user friendly. In relation to #204, the tooltip reads "separate each entity with a comma," then goes into an example. The wording is confusing since it sounds like the example is referring to how to add a comma to add more entities. Perhaps add that section after the example is given.

Additionally, example uri's can be improved. They are a little confusing to users, because they all look identical across different datafields since they all use "example.com." Real, already used examples would be better than such as, "https://credentialengineregistry.org/" for Creator.

**Comment by chinhseah** [comment]
Thanks @eddavies for the feedback. I can easily move the "separate each entity with a comma" after the example. But I don't know where to find real URIs for examples that I had listed above. Can you let me know where I can lookup real URIs I can use as examples?

**Comment by eddavies** [comment]
License and identifier can stay that the same. For all of the others, theoretically, https://credentialengineregistry.org/, https://eduworks.com, https://case.georgiastandards.org/, could be used (multiple times each) for the others I think. @Lomilar would this be ok?

**Comment by eddavies** [comment]
Should be "for example:" instead of "for example," unless my grammar is wrong.

**Comment by eddavies** [comment]
Instead of "Separate each entity with commas" should it be: "Separate each entity with a comma"?

**Comment by eddavies** [comment]
Making notes for tooltips in this thread now:
Source framework: replace "original" with "original framework"
Note (in concept): replace "change" with "note" or "change note"
Need tooltips for connections in the concept editor (this can be a new issue)

In concept scheme, Publisher name does not have a tooltip
concept scheme needs their tooltips (creator, publisher, language, change note (that is under context, and needs tooltip change for with a comma)) to be changed to "separate each entity with a comma"

**Comment by eddavies** [comment]
fix verified
