### ISSUE TITLE
DateValidFrom and DateValidUntil in CTDL+ASN are date, not datetime.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#217]
However, in Schema.org, validFrom and validThrough are datetime. Check mappings.

**Comment by Lomilar** [comment]
* Ensure dates are making it to the CEASN export.
* See how or if non-ceasn datetimes migrate to ceasn dates.
* Ensure input for ceasn mode works okay.

**Comment by Lomilar** [comment]
@siuc-nate @stuartasutton Hey,

I'm noticing that dateCreated, dateValidFrom and dateValidUntil are xsd:date. This creates a level of unspecified behavior around timezones and whether things are valid on the date of expiration.

It also makes them incompatible with schema:validFrom and schema:validUntil and schema:dateCreated.

Can you remind me why this is taking place?

**Comment by stuartasutton** [comment]
This  thread started with a request that dates be more "permissive", not that date/time shouldn't be there.

**Comment by Lomilar** [comment]
Got it. Thanks.
* When entering a date, should auto-fill time if possible and not invalidate.

**Comment by stuartasutton** [comment]
Hmmm. What do you think?

**Comment by siuc-nate** [comment]
This one is tricky. I can see the validity in the point Fritz raises in terms of timezones, but at the same time, I don't know how likely it is that anyone would know what to put in for the time field anyway - or that it would necessarily matter in our context since CASS wouldn't be (as far as I know) doing anything with the date field aside from storing it.  I think it's probably fine to capture _just_ the date, as that may be more user-friendly, but if (as Fritz suggests) the time can be autofilled (based on the user's browser's timezone?), maybe that's worthwhile?

There is also the question of the schema - if the field's range is defined as date rather than datetime, is a consuming system going to expect time data to be there as well?  In CTDL, we changed all of the datetime fields to date at one point, so this would create a bit of minor inconsistency between CTDL and CTDL-ASN (when it's exported from CASS) - but then maybe it's not something that would cause a problem.

I don't currently have a strong opinion either way. I can see reasons to take either route.

**Comment by Lomilar** [comment]
For systems that use time, the underspecificity of the time requires a system to assume the time, so this could result in things like:

* A license expiring at different times depending on the timezone of the web browser, server, or other machine.
* Creating some sort of error when observing the dateCreated because it is interpreted in GMT, causing frameworks to have been 'created tomorrow' or other strange things, because one system interprets no time as GMT 00:00 and another interprets no time as Local 00:00

From a schema perspective, `ceasn:dateValidFrom` and `ceasn:dateValidUntil` are now incompatible with `schema:validFrom` and `schema:validUntil`, who'se range is xsd:dateTime. This is more an annoyance than a real issue, as it causes data loss when converting to CTDL-ASN and back.

**Comment by Lomilar** [comment]
Todo: Verify this.

**Comment by stuartasutton** [comment]
I thought we had already done that.

**Comment by Lomilar** [comment]
We may need to update translation schemas on our side for it to be happy... but I am starting to recall doing this. Probably worth another check just in case.

**Comment by Lomilar** [comment]
dateValidFrom and dateValidUntil need changing back to datetimes in the CaSS Editor.

**Comment by Lomilar** [comment]
@woodkri 
Errors displaying new dates? Errors displaying old date types?

https://cassproject.github.io/cass-editor/?ceasnDataFields=true&frameworkId=http://not.here/045e2380-6b48-4145-bc21-46895087dfa3

**Comment by woodkri** [comment]
@lomilar New dates and old date types are displaying without errors for me. The framework you linked definitely has some problems but it looks like they were happening before the change to datetime. I'll investigate and see if I can figure out what is going on there.

**Comment by siuc-nate** [comment]
@Lomilar Can you verify that this is finished?

Thanks.

**Comment by Lomilar** [comment]
Still seems to be working. Any reason to think it may not be?
