### ISSUE TITLE
CSV upload doesn't prepopulate IDs with http data if none exists.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#275]

**Comment by woodkri** [comment]
Reproduced: 
![after importing non-url ids - competency with no http](https://user-images.githubusercontent.com/33300923/48158747-4c267180-e2a1-11e8-9fba-77029357e054.PNG)

It seems like this is an issue for cassproject/CASS. The call to CSVImport.transformId (currently line 1048 of cass.import.js) doesn't do anything in this case, since the id is not null or empty and doesn't include http.

**Comment by eddavies** [comment]
fix verified
