### ISSUE TITLE
Concept scheme editor, "+" icon does not do anything

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#276]
While searching for a concept term or level/level type, the "+" icon to create your own concept scheme is not working.

**Comment by chinhseah** [comment]
When I traced in Chrome browser, the "+" icon code is in index.html line 200.
That calls createFramework() in line 281 of editFramework.js.
Because in conceptMode, calls createConceptScheme on line 52 of editConcept.js.
But line 54 $("#name").val() == null is true so just return and so "does not do anything".
I could not find input with id = name so not sure where value should come from??

**Comment by eddavies** [comment]
Fix verified.
