### ISSUE TITLE
Empty Framework Bug

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#327]
![empty framework bug](https://user-images.githubusercontent.com/23706850/41989745-2d9ffbd8-79f5-11e8-9522-74cd7ff71b50.PNG)
Attempting to reproduce. Occurred after creating a narrow alignment with a competency that parents it.

**Comment by stuartasutton** [comment]
Has happened to me on occasion...

**Comment by eddavies** [comment]
So I was able to reproduce by:
1. creating a framework with competency 1 and competency 2 as a child of competency 1
2. under connections for competency 2, went to create a new narrow alignment
3. Made the narrow alignment with competency 1
4. The bug occurred.

**Comment by chinhseah** [comment]
@miledivovic I was able to re-produce this issue after following @eddavies 's steps mentioned. I just want to add screen capture for selecting competency 1 as alignment for competency 2.
![cass-editor-select-alignment](https://user-images.githubusercontent.com/15805943/42528631-f60978ac-8430-11e8-848b-9a17d00bf114.png)

**Comment by chinhseah** [comment]
@eddavies @miledivovic Is this expected behavior? If I didn't save Competency 2, child of Competency 1, before going back to edit Competency 2 to add a Narrow Alignment, I got a pop-up dialog box message saying, "Some data has changed during edit. Do you want to discard changes?"
![dialog box discard changes](https://user-images.githubusercontent.com/15805943/42528888-c965be7c-8431-11e8-814d-00b35d664ddf.JPG)

**Comment by eddavies** [comment]
still occurs. fix rejected

**Comment by eddavies** [comment]
fix verified
