### ISSUE TITLE
View category labels should match Edit category labels.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#329]
CredentialEngine/CompetencyFrameworks#68

**Comment by miledivovic** [comment]
This is the same issue as #312 right?

**Comment by Lomilar** [comment]
Yes.

**Comment by eddavies** [comment]
Closing this, #312 was fixed.

**Comment by eddavies** [comment]
@stuartasutton I can see it both on the cass-editor test server and on http://ctitest.siuccwd.com/competencies
From my understanding this issue is related to the ability to view the section headings (such as: tagging, scales, and connections) while in view mode, only if there are existing entries under the header. Is this incorrect?

**Comment by eddavies** [comment]
from our test server:
![can see not bug](https://user-images.githubusercontent.com/23706850/42351838-e08d6b28-806b-11e8-959a-1c808a5731e7.PNG)
Meaning the: "Properties," "Tagging," "Connections," "Context," "Rights" correct?

**Comment by stuartasutton** [comment]
OK, I'm supposed to have access to test servers and obviously don't.

**Comment by Lomilar** [comment]
@eddavies In this case, view mode means just viewing the framework/competency, not `view=true`.

That term may be overloaded in this conversation and causing confusion.

@stuartasutton Apologies for the confusion here. "View Mode" internally refers to [when this configuration option](https://github.com/cassproject/cass-editor#view-mode) is set.

**Comment by stuartasutton** [comment]
@eddavies, almost correct. There is no "Properties", the top category is "General". See tables at the bottom of https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803 starting at row 35

**Comment by Lomilar** [comment]
Just noticed what Stuart said above as well.

**Comment by stuartasutton** [comment]
@eddavies, you ask: "From my understanding this issue is related to the ability to view the section headings (such as: tagging, scales, and connections) while in view mode, only if there are existing entries under the header. Is this incorrect?"

No, that is correct. When in end user view mode, only those section heading should appear where there is data in one of the sections properties...then only those properties that have data (no empty properties). Does that make sense?

**Comment by stuartasutton** [comment]
@eddavies, when looking at the spreadsheet at https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803 , note that there is a section above "General" as discussed in https://github.com/CredentialEngine/CompetencyFrameworks/issues/67 called (for now) "Record Keys" and contains the "Framework URL" and the "CTID".  Issue https://github.com/CredentialEngine/CompetencyFrameworks/issues/67 discusses how those two properties under "Record Keys" might be handled graphically. 

This would also be true handling the "Competency URL" and CTID.

**Comment by eddavies** [comment]
Ok, yes that makes sense. Apologies for my misunderstanding. So we need to add the "Record Keys" label and change "Properties" to "General"

**Comment by stuartasutton** [comment]
And create a new "Keys" category above "General" and move the following to this new category:

1. "Competency URL" & "CTID"
2.  "Framework URL" &CTID

**Comment by miledivovic** [comment]
@eddavies @stuartasutton Thanks for the clarification, these changes should be on the test server now. http://ctitest.siuccwd.com/competencies

**Comment by stuartasutton** [comment]
Yes, they are there.

**Comment by eddavies** [comment]
All labels for fields and categories are visible in view mode and should match the mappings in the spreadsheet. Please feel free to reopen if any concerns with this are found.
