### ISSUE TITLE
Friendlier "Keys" property group.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#356]
@stuartasutton Should the keys panel default to collapsed? I think its fine up at the top, but it does kinda put technical things before the name of the competency.

![image](https://user-images.githubusercontent.com/337692/43231076-a63fb5f2-901f-11e8-8d84-174ffb07b6b3.png)

**Comment by stuartasutton** [comment]
Keys defaulting to collapsed is kind of OK except for the fact that it isn't in sync with other section where collapsed means no data present in that cluster.  I also suggested, however, that the Keys section be made less conspicuous by reducing the font and the leading (spacing) so that the greyed box takes up less real estate. Adding the 'copy to clipboard' icon to both URL and CTID would be helpful.

**Comment by Lomilar** [comment]
Having it expanded the first time, to say hey, here I am, and allow for itself to be collapsed (and stay collapsed) would probably be a good compromise. +1 on the copy to clipboard icon. +1 on reduction of gray box spacing.

**Comment by eddavies** [comment]
When searching for existing competencies to add to a framework or for concepts, the keys category is a bit smaller. Is this intended?
