### ISSUE TITLE
Move listID on competencies from bottom of Context cluster to bottom of "General" cluster

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#364]
To facilitate ease of repetitive entry, move the `listID` from the the bottom of the "Context" cluster where it is now to the bottom of the "General" section. I.e., from here:
<img width="1132" alt="screenshot 2018-08-01 08 48 18" src="https://user-images.githubusercontent.com/2939046/43532646-f6de13da-9567-11e8-9260-ca4f33728d31.png">

To the bottom of this:

<img width="1129" alt="screenshot 2018-08-01 08 57 42" src="https://user-images.githubusercontent.com/2939046/43533185-17a72cc2-9569-11e8-9068-4f73c9f88e3c.png">

**Comment by Lomilar** [comment]
The context tab is certainly where this belongs. Is the issue that there's some additional clicking/scrolling that needs to happen to get to this entry?

Just looking to understand the workflow issue a bit more, otherwise it seems like most of the fields in Context would move up into General (as Competency Category has)

**Comment by stuartasutton** [comment]
@Lomilar, the General tab is where properties of both primary concern and consistent use properties belong. Moving `listID` to the bottom of General is because a high percentage of competencies have the data justifying the move so the people entering data can avoid a persistent scrolling operation.

**Comment by Lomilar** [comment]
+1 - No barriers here, just double checking.

**Comment by eddavies** [comment]
ListID is now under the general section.
