### ISSUE TITLE
CSV import of Concept Schemes

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#378]

**Comment by Lomilar** [comment]
1082ceaad091e785013958ddceff0e163e102794

**Comment by woodkri** [comment]
This is ready to be merged into master after the feature/jsonldcompactcsv branch is merged into EC.

**Comment by woodkri** [comment]
@Lomilar I had this working locally but it won't work on cassproject.github.io because the context translations are http rather than https. Is it possible to serve the schema files over https, or is there something else that would fix this?

The same problem is happening for csv framework imports - #509

**Comment by Lomilar** [comment]
Try using the https URL (we need to allow HTTPS on schema.cassproject.org) and see if it blows up.

If that doesn't work...

This is a workaround - We need to do this processing on the server, we could also override the get code in jsonld.js, we could also internalize all the context files

**Comment by eddavies** [comment]
@woodkri Is there a sample concept scheme CSV file that I can test with?

**Comment by eddavies** [comment]
I can't seem to import the sample CSV Concept Scheme. 

I get this screen:

![import](https://user-images.githubusercontent.com/23706850/61315923-b094bb80-a7b4-11e9-8b75-938a573aa008.PNG)

But then instead of importing I get redirected to the import screen again: 

![sample not importing](https://user-images.githubusercontent.com/23706850/61316501-faca6c80-a7b5-11e9-823a-44e92a052355.PNG)


However, if I make changes to the CSV sample and then import it. I am correctly redirected to new concept scheme. 

We need some sort of error message for users who use the sample csv import file (I assume this is an ownership issue because the concept scheme already exists?).

**Comment by eddavies** [comment]
In short, issue arise from importing a concept scheme that already exists. But works fine for ones that don't.

**Comment by eddavies** [comment]
Error message is appearing now. Closing this.
