### ISSUE TITLE
Import tutorials usability

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#381]
The import page could use some better styling or formatting. The CASE import is practically difficult to see at first glance. There are large spaces between text in the tutorials. The CASE and OpenSalt import should have a confirm or enter button, simply pasting something and causing a next step is awkward.

**Comment by Lomilar** [comment]
Lookin for feedback.

**Comment by Lomilar** [comment]
I was avoiding eating up the white space because columns are easier to read than text that goes all the way across the screen. We are also introducing (at some point) the ability to import frameworks from other types of servers, say, other CaSS repositories.

I'll increase the URL paste box size.

I don't know about the rest of the styling to be honest, would love a third opinion here. Centered looked weird, right justified looked like it could be missed, left justified looked a bit crammed.

The functional reason to have the URL bar auto-advance was so when people are typing in a URL, it just advances when they have typed in enough of the URL.

**Comment by eddavies** [comment]
Looks fine on ctitest
