### ISSUE TITLE
Keyboard Up Down Arrows Selects Wrong Competency After Collapsed

### ISSUE THREAD

**Issue by chinhseah** [cassproject/cass-editor#400]
I found this issue while performing additional testing for issue #366. It could be related to issue #297 but I do not "see cross domain errors appear in Developer Tools Console" commented by @Lomilar. I open this issue just for strange behavior when using up/down keyboard keys to select competencies within a framework displayed. 

1) 1st collapse my test "Competency 2B":
![collapse competency 2b](https://user-images.githubusercontent.com/15805943/47184691-30eac680-d2e0-11e8-9369-428eeb602e92.PNG)

2) Selected my test Framework:
![select framework post collapse](https://user-images.githubusercontent.com/15805943/47184738-54157600-d2e0-11e8-8ea8-8105076cc2c1.PNG)

3) Chose/typed down arrow on my keyboard. Instead of selecting "Competency 2A" as expected, "Competency 2C" got selected. "Competency 2A" should have been selected.
![down arrow selects competency 2c](https://user-images.githubusercontent.com/15805943/47184914-d3a34500-d2e0-11e8-89b0-801d74042541.PNG)

**Comment by chinhseah** [comment]
I also found that when Framework first gets displayed, from clicking on/selecting it from list of Frameworks, that 1st press of Down arrow doesn't do anything and only on 2nd press of Down arrow will a Competency within Framework gets selected.

**Comment by chinhseah** [comment]
@eddavies Please test out pressing left or right arrow keys after you have selected a competency that is collapsible and expandable. Thanks.

**Comment by eddavies** [comment]
I can't seem to get any of the arrow keys to work on ctitest. I'll try testing this on cass test though.

**Comment by eddavies** [comment]
This works on cass test.
Arrow keys are not functional on ctitest.

**Comment by siuc-nate** [comment]
I thought we had resolved this already.  Did it just fall through the cracks instead?

**Comment by Lomilar** [comment]
IIRC, the solution was to copy a version of cass-editor to ctitest and keep it up to date. This would remove some of the testing benefits of ctitest pointing directly at github's latest version of the editor. 

Now that I think about it, we may have decided explicitly not to fix this because of the hassle it would create during testing.

I'm okay with reinforcing this as a known issue for CTITest, it does seem to happen on production as well though. That we can solve by moving the place where cass-editor is shared from the cass.credentialengine.org domain name to the same one the publisher is on (credentialengine.org).
