### ISSUE TITLE
First competency of a new framework is invisible

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#402]
This does not occur consistently. It appears to happen more often after creating a framework and adding a new competency quickly.

![afdsaeef](https://user-images.githubusercontent.com/23706850/47236004-9ba70b00-d38f-11e8-8e2e-c07843afaf1a.PNG)

This is what happens after saving the competency.

![competency save](https://user-images.githubusercontent.com/23706850/47236006-9cd83800-d38f-11e8-8416-e030049faf58.PNG)

**Comment by chinhseah** [comment]
@eddavies I haven't been able to re-produce this issue. As discussed, based on screen capture you provided, I think this happened because data was returning from Opensalt URL while you were creating a new Framework even though you may have thought you canceled import. I think this will not happen now that issue #401 is fixed.

**Comment by eddavies** [comment]
@chinhseah Ok that would make sense. I'm testing the fix for #401 now and will test this right afterwards.

**Comment by eddavies** [comment]
closing this, dependant on #401
