### ISSUE TITLE
Increase transparency of concept scheme overlay to show context (the framework that is being edited).

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#478]

**Comment by Lomilar** [comment]
Apply as well to other iframes.

**Comment by Lomilar** [comment]
- [ ] Relation choice
- [ ] Select competencies to add to this framework

**Comment by woodkri** [comment]
Thoughts on this?

![div overlay](https://user-images.githubusercontent.com/33300923/51941002-79d31080-23e1-11e9-8d9a-604e004f67d0.PNG)

**Comment by Lomilar** [comment]
Try out a black 50% transparent.

**Comment by Lomilar** [comment]
Do the display:none removal for the editFramework panel and z-index things to make this work, and allow the implementer to configure via css.

**Comment by woodkri** [comment]
The css of the "transparent" class can now be manipulated to change the edit framework section behind the overlay. I have it set to "display: none" for us so that it doesn't show at all. The top example was "opacity: 0.5", and the bottom was "background: rgba(0, 0, 0, 0.5)". For the bottom example, the white background for the sidebar toolbar was removed as well, and text-shadow was added to the header text.

**Comment by Lomilar** [comment]
Tested. Works. To be included in 1.0.6.
