### ISSUE TITLE
Competencies sent to parent window via postMessage (via "add" button) sometimes use expanded language maps

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#497]
we haven't been able to nail down a pattern yet, but some competencies yield data that uses expanded language maps (e.g. using `@language` and `@value` properties) when sent to the parent window via postMessage after the "add" button is clicked:
![image](https://user-images.githubusercontent.com/21346519/52869701-dc2f4f00-310b-11e9-9913-9f5c5e678627.png)

It is sometimes inconsistent even within a framework:
![image](https://user-images.githubusercontent.com/21346519/52869857-3c25f580-310c-11e9-9a95-16cd30d20316.png)

Note: This is preventing some of our partners from being able to align their credentials/assessments/learning opportunities to competencies.

**Comment by cwd-mparsons** [comment]
@Lomilar 
NOTE: Our preferred data type would be to continue with the name being provided as a simple string.

**Comment by Lomilar** [comment]
This is, unfortunately, valid JSON-LD. We have libraries and methods for pulling display strings out of a field that may contain language maps entered by the editor, an import (such as the CTDL-ASN import) or elsewhere.

```html
<script src="https://cdn.jsdelivr.net/gh/cassproject/cass@1.0.7/src/main/js/cass.js"></script>
<script>
  var name = null;
  var json = {} //Set from the function that captures the .
  var rld = new EcRemoteLinkedData();
  rld.copyFrom(json);
  if (rld.isAny(new EcFramework().getTypes()))
  {
    //We're dealing with a framework.
    var f = new EcFramework();
    f.copyFrom(rld);
    name = f.getName();
  }
  else if (rld.isAny(new EcCompetency().getTypes()))
  {
    //We're dealing with a competency.
    var c = new EcCompetency();
    c.copyFrom(rld);
    name = c.getName();
  }
</script>
```

I don't think we're going to be seeing fewer langstrings, and changing the objects would cause signature validation to fail.

**Comment by siuc-nate** [comment]
As long as the data returned is consistent, we should be able to deal with it. I would prefer the language map style we've been working with (e.g. `{ "en-us": "some value" }`) over the expanded form (with `@language` and `@value` properties), but it isn't a huge deal either way.

**Comment by Lomilar** [comment]
Given we identify our fields using schema.org and they don't specify langstrings for any of their data, neither do we in our schema. This gives us more flexibility in handling diverse data from multiple sources, but it does mean that every field fetch has to be checked and double checked. That's why we use getters in our library and strongly encourage using the library.

And the data isn't consistent, also because it can come from diverse sources.

Sorry. I promise using the getter to get a display string will be the better option in the long term, especially as CE expands overseas, as we will be using the browser settings to identify which display string to show.

**Comment by siuc-nate** [comment]
I thought the competencies were supposed to be exported in the schema that was selected via the iframe's GET parameters (e.g. the ctdl-asn schema)?  Wouldn't that resolve the issue?

**Comment by Lomilar** [comment]
We could do that as an optional parameter for the select mode.

**Comment by woodkri** [comment]
If we're displaying in CTDL-ASN schema, there would still be langstrings. They would just be in the CTDL-ASN format of "en-US": "Framework" versus {"@language": "en-US", "@value": "Framework"}. Should the name be only one value with no language in this mode instead?

**Comment by cwd-mparsons** [comment]
Nate has added code to check the format of the name and comment. The code checks for a string, an object in the CTDL-ASN format, or the {"@language": "en-US", "@value": "competency"} format.
So as long as the data is supplied in one of the latter three formats, we should be fine.

**Comment by Lomilar** [comment]
@cwd-mparsons @siuc-nate I believe those three formats are the only three ways that a string can be represented in JSON-LD.

**Comment by Lomilar** [comment]
Oh, there's also
```json
["String 1","String 2"]
```

**Comment by woodkri** [comment]
@eddavies There's a new URL parameter selectExport=ctdlasn that sends the "selected" message to the console and parent window in Credential Engine's schema. This message is displayed when adding a relation (exact alignment, for example) or with the "Attach subitems from other sources to the selected item" button. It should work with or without selectVerbose=true but does not yet work for concepts since we don't have concept scheme CE export functionality yet.

**Comment by Lomilar** [comment]
This concludes work on the cass-editor side of things to address this issue. It has been patched already, so that it isn't a problem on production.

Documentation is here.
https://github.com/cassproject/cass-editor#change-schema-for-selected-postmessage
