### ISSUE TITLE
Import and Production editor doesn't allow entry of registered (®) symbol

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#505]
I created an import file for Certified Fiber Optics installed. Several of the competencies included the registered symbol. 
![image](https://user-images.githubusercontent.com/26332112/53771486-57cd2200-3ea8-11e9-9817-2d02336ce02e.png)

The import process on both the dev server and production did not import the symbol, instead substituting a question mark. 
On the test server I was able to manually edit the affected competencies, and add the registered symbol. 
I imported the same file into production. However, any attempt to add the registered symbol is rejected. 
Note the save initially appears to work, and then on refresh, the symbol is replace by the default symbol of a question mark on a black diamond. 
![image](https://user-images.githubusercontent.com/26332112/53771704-48020d80-3ea9-11e9-8c99-9ea1d04d1a4e.png)

**Comment by stuartasutton** [comment]
I was going to post a similar issue but can ride I think on this one. AS I was doing some testing on the ConceptScheme  editor, I came to doubt whether we were supporting UTF8. Check the following French text:

```
{
     "@language": "fr",
     "@value": "Science des communications et des syst?mes de contr?le automatique dans les machines et les ?tres vivants."
}
```
Should be...

 "Science des communications et des systèmes de contrôle automatique dans les machines et les êtres vivants."

Copyright symbol falls into the same bailiwick. Here it is from my test:

```
"dcterms:rights": "?2019 All rights reserved.",
```
instead of:

"dcterms:rights": "©2019 All rights reserved.",
```

**Comment by Lomilar** [comment]
This should be fixed with changes made locally to the installation.

For the sake of future viewers: The change was that windows versions of Tomcat default to the Windows character set instead of UTF-8. A configuration setting in tomcat (-Dfile.encoding=UTF8 I think?) remedied the problem.
