### ISSUE TITLE
Test import of CTDL Concept Schemes

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#514]
@siuc-nate @cwd-mparsons 
Can you provide links to the concept schemes, we can test importing them and then @cwd-mparsons can test publishing.

**Comment by Lomilar** [comment]
https://credreg.net/ctdl/terms/Audience/json is one of them.

**Comment by siuc-nate** [comment]
Using the JSON encodings from https://credreg.net/ctdl/terms#conceptschemes
 
https://credreg.net/ctdl/terms/ActionStatus
https://credreg.net/ctdl/terms/AgentSector
https://credreg.net/ctdl/terms/AgentServiceType
https://credreg.net/ctdl/terms/AssessmentMethod
https://credreg.net/ctdl/terms/AssessmentUse
https://credreg.net/ctdl/terms/Audience
https://credreg.net/ctdl/terms/AudienceLevel
https://credreg.net/ctdl/terms/ClaimType
https://credreg.net/ctdl/terms/CostType
https://credreg.net/ctdl/terms/CredentialStatus
https://credreg.net/ctdl/terms/CreditUnit
https://credreg.net/ctdl/terms/Delivery
https://credreg.net/ctdl/terms/ExternalInput
https://credreg.net/ctdl/terms/IntendedPurpose
https://credreg.net/ctdl/terms/LearningMethod
https://credreg.net/ctdl/terms/OrganizationType
https://credreg.net/ctdl/terms/Residency
https://credreg.net/ctdl/terms/ScoringMethod

Note:
- I still need to implement the changes to the encoding we discussed in emails to use the correct property for pointing to the history URI.  I'll post an update here when I have done so.
- It may be useful to include the meta:hasConcept data, as Audience Level and Organization Type are not flat concept schemes, but since the graphs above each return all of the concepts for a given scheme, this may be redundant anyway.

**Comment by stuartasutton** [comment]
Nate, I do not think the meta:hasConcept is necessary.

**Comment by siuc-nate** [comment]
We should probably go without it for now.  

If we did end up needing it for some reason, it would be better to do so as a proper CTDL-ASN property anyway.

**Comment by stuartasutton** [comment]
I agree. But many years of experience have demonstrated no call for it.

**Comment by stuartasutton** [comment]
The spreadsheet at https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1140243756 has us using ceasn:publicationStatusType and the http://purl.org/ctdlasn/terms/PublicationStatus vocabulary

**Comment by cwd-mparsons** [comment]
I had added Audience to the test concept editor. I had to massage the data a little for properties with an incorrect/unhandled data type.
Following is a link to the concept scheme in the sandbox. 
https://sandbox.credentialengineregistry.org/envelopes/a43467b4-0b8a-4397-b69e-9992c78801c8

Regarding the format of data from credReg:
https://credreg.net/ctdl/terms/Audience/json

The data of course doesn't have URIs or CTIDs. I thought about adding an API endpoint that accepts either a list of URIs or a list of concept schema name, and resolve the latter to URIs. 
However, this type of publishing could be one time only. As, if the API is generating CTIDs for the publish, the next publish attempt with same input would generate another set of CTIDs and we would have a duplicate concept scheme. 
OR, we could generate the CTID using an MD5 has of the @id (i.e. audience:Citizen = 73A04A89E56CF9F7FE014E76DBFB3371)

**Comment by Lomilar** [comment]
The @ids being http://purl.org/ctdl/vocabs/audience/Citizen is supported on the CaSS side, which isn't a registry URL. So, based on current policies, these vocabularies would be assigned CTIDs and registry URLs and the CTID would be a UUID3 derived from the MD5 of the @id. (so you were very close, Mike).

**Comment by Lomilar** [comment]
The conclusion of this will satisfy #104

**Comment by Lomilar** [comment]
The export has no association back to the canonical @ids. 

- [ ] We need to link back to the canonical @id via an exact match during the export if the @id changes.

@cwd-mparsons Did you take the data you published from an import/export to CaSS?

**Comment by Lomilar** [comment]
Been testing this. Got it working (locally) just now.

**Comment by stuartasutton** [comment]
Still hoping to demo these in the Finder during the Friday TAG.

**Comment by Lomilar** [comment]
- [ ] Needs

 to assign permissions in a similar fashion to CTDL-ASN import (overall owner from config, importing organization)

**Comment by Lomilar** [comment]
The imported schemes are showing up in a direct query (?q=...) but are not showing up on Dev in a search.

Also unable to scroll past the initial resultset.

**Comment by Lomilar** [comment]
[CE Terms.zip](https://github.com/cassproject/cass-editor/files/3015115/CE.Terms.zip)

**Comment by stuartasutton** [comment]
Thanks @Lomilar, I've done a quick review and find most are spot on. Here are the issues:

1. **Collapsing skos:definition and comment.** Some of the (original) ConceptSchemes have both a definition  rdfs:comment and dct:description. Since the skos encoding for ConceptScheme only has ceasn:description, the original comment text has been added as a second instance of ceasn:description. It's a problem only because one is normative and the other not AND the order of entry gives the non-normative the top spot in display. 

2. **Missing broader/narrower.** Both `OrganizationType` and `AudienceLevel` have concepts with broader/narrower relationships. The narrower nodes are missing. Here's the `AudienceLevel`
```
AdvancedLevel
BeginnerLevel
IntermediateLevel
SecondaryLevel
PostSecondaryLevel
   AssociateDegreeLevel
   BachelorsDegreeLevel
   MastersDegreeLevel
   DoctoralDegreeLevel
```

3. **Error on Download.** Getting error message on download (e.g., for OrganizaitonType: "TypeError: Cannot get property "ceterms:ctid" of null")

**Comment by stuartasutton** [comment]
I just caught another issue, @Lomilar & @siuc-nate. The vocabulary for ClaimType is including its deprecated concept.

**Comment by woodkri** [comment]
1. Is my understanding correct that in this case rdfs:comment is what should map to ceasn:description? What would dct:description map to on the Credential Engine side?

2. CaSS manages broader/narrower relationships by starting at the top level and looking for "skos:topConceptOf" and "skos:narrower" properties. These two frameworks appear to have "skos:broader" but not "skos:narrower". Is this a common pattern or an error in the source data?

3. Download error seems to be caused by the vann:usageNote field. I'll work on a fix in the schema for this.

**Comment by cwd-mparsons** [comment]
The property dct:description would be ignored at this time. As would usageNote.

**Comment by stuartasutton** [comment]
@woodkri, as for no. 2, no, it should not be a pattern. In skos, where ever there is a `skos:broader`, there should be a `skos:narrower`.

**Comment by woodkri** [comment]
What field should be used to link back to the canonical id for a concept scheme? skos:exactMatch does not apply at the scheme level.

The rest of the issues raised here can be tested upon the next deployment to dev, with these exceptions:

1. The import data does not have skos:narrower fields so the hierarchy is not rendered.
2. Stuart mentioned a deprecated concept that is included.

I'm not sure where the import files came from, can they be edited to fix these data issues?

**Comment by Lomilar** [comment]
To create issue in CredentialEngine/vocabularies to finish up #1 and #2 from Apr 8 comment. Close when issue is created.
