### ISSUE TITLE
Some frameworks in production have had the inLanguage tag set to empty.

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#548]
Stuart had noted several frameworks that were missing inLanguage. 
I did a download of all frameworks and didn't find any without inLanguage. 
I then started randomly checking frameworks **in production**.
I would find some that had an empty inLanguage. 
At first, I started to update and republish. Then I started to check the current document in the registry. In all cases (> 5), the registry document did have an inLanguage tag. In the cases I checked, the value was en. 
Did some process clear out the language tags, maybe based on not have a value of say en-US? The latter is just a stab as to what could have happened.

First have to determine what happened, and ensure it doesn't happen again. 
Then can consider updating all frameworks with missing inLanguage to 'en-US'.

**Comment by woodkri** [comment]
@cwd-mparsons It looks like there are 258 frameworks alone with no inLanguage field on production. Do all of the competencies, concept schemes and concepts also need to have that field set? And will you need the ids to republish, or is that not necessary since the publishing process added a language field already?

**Comment by siuc-nate** [comment]
Per our 5-29-2019 meeting:
The CASS interface should insert the framework's selected language into each of its competencies' `inLanguage` property by default when the competency is created.

**Comment by woodkri** [comment]
Next steps: Set inLanguage field to English for frameworks, competencies, concept schemes and concepts. Ids are not needed to republish.

**Comment by woodkri** [comment]
The script has been run.

@cwd-mparsons @siuc-nate We're currently setting the language as part of the CTDL-ASN JSON-LD export process if it isn't already set. Do you want that to be taken out so that there's an error when you try to publish if the language isn't present?

I also noticed a lot of these frameworks were imported. Should a language be added as part of the import process?

**Comment by siuc-nate** [comment]
Inserting the language during export seems right to me but your questions are really more in @jkitchensSIUC and @stuartasutton's domain.

**Comment by stuartasutton** [comment]
I'm not solid on what is being asked. I can say definitively, the backlog of frameworks without an inLanguage tag need to be brought into compliance. Does the question go beyond that?

**Comment by woodkri** [comment]
I've added inLanguage to existing frameworks that didn't have it. There could be frameworks added in the future that don't have that field though, so I'm wondering if we should continue to set inLanguage as part of the export as we have been doing or if we should remove that. Mike had suggested the possibility above of removing that step in the export so that the absence of inLanguage isn't hidden.

**Comment by cwd-mparsons** [comment]
@woodkri re: import
Yes, I think that having the import populate the inLanguage would be useful. 
We don't want a user to have to edit each competency to add the language.

**Comment by Lomilar** [comment]
We can accomplish this by having default values (inLanguage, etc) set at the server side for server created data via 

`EcCompetency.template["ceasn:inLanguage"] = ...`

as part of a server side config.

**Comment by Lomilar** [comment]
Hey me, was this done?

**Comment by Lomilar** [comment]
Not yet done. Do, test.

**Comment by cwd-mparsons** [comment]
@Lomilar Is this completed?

**Comment by Lomilar** [comment]
Tested this with CASE imports, it didn't work for me. @woodkri Can you investigate further? (plop a file in /etc/foo.js with `EcCompetency.template["ceasn:inLanguage"] = "en-US"` and see why the objects being created aren't getting populated with the template?

**Comment by woodkri** [comment]
The templates can be set like this:
EcFramework.template = {"schema:inLanguage": "fr", "schema:dateCreated": ""};
EcCompetency.template = {"schema:dateCreated": ""};
EcConceptScheme.template = {"dcterms:language": "fr", "schema:dateCreated": ""};
EcConcept.template = {"schema:dateCreated": ""};

Using that format, the object constructor included the template fields, but the use of copyFrom to cast the imported data to CaSS objects is wiping the fields away. There may be another way to preserve the fields from the template, but for now I'm adding in a check for the presence of "schema:inLanguage" in the template as part of the CASE import.

Since language properties will be removed from competency and concept, I've only included schema:dateCreated (#534) for those.

**Comment by Lomilar** [comment]
This should be a configurable option. Default parameters overriding imported data is not going to always be a desired thing, and this is a bit of a one-off.

**Comment by woodkri** [comment]
I'm not sure I follow. If the import has a language field, it's not being overwritten here. It was my understanding that this was to be used to set a language on frameworks/concept schemes that don't have one, so that's how I've implemented it. If that's not the intent, I can change it so it does override the imported data.

When you say it should be a configurable option, do you mean whether the import data is overwritten, or something else?

**Comment by Lomilar** [comment]
Sorry, I didn't explain why I have this thought.

Having no data can be a discrete choice to make something unspecified. A language being unspecified means that it isn't clear, and overriding that with en-US forces something as being "in US English" that may not have been (because it was imported from a Japanese server), so, this is a policy level decision, not a system level decision, so it should probably be configurable.

Whether the template level data is copied into imported data (if the imported data doesn't specify something) should be a configurable option.

**Comment by woodkri** [comment]
I'm having a hard time thinking of a use case where someone would want to set the language in the template but then not have it override an unspecified language. It seems like that's the point of setting the template (at least server-side) so someone with that intent could just not define a template.

I could add in another check, something like if EcFramework.template["schema:inLanguage"] != null && templateOverride == true. If the language is set in the template though and templateOverride is not true, nothing would happen so the template may as well not be set.

Or do you mean it should be configurable client-side for each import and sent as part of the request to the server? If that's the case it almost seems like we may as well pass a language in (or null) instead of defining a template on the server.

**Comment by Lomilar** [comment]
Fair point on that second paragraph. Nix the need to make it configurable, you are right.

**Comment by Lomilar** [comment]
OK. This change is in version 1.2.23
