### ISSUE TITLE
Editor listing of frameworks lack a principle of order

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#57]
Currently, when the editor is launched, there is no principle of order (alpha, last in...). Since the number of frameworks could be large, alpha order seems best to me.

**Comment by eddavies** [comment]
Frameworks that start with lowercase letters appear at the bottom of the list

**Comment by stuartasutton** [comment]
@Lomilar, @eddavies, & @jkitchensSIUC: 

I'm sorry, I should have said, a "useful" principle of order in sorting the competencies and the concepts indexes browsers. An alpha sort (including (exacerbated by)  a bifurcated sort based on capitalization) will be of little use when the registry exceeds 5,000-10,000 frameworks of concept schemes. 

Is there any way to facet the browse so it can be sorted based on other parameters such as by an alpha list of owners, a simple alpha list, by occupation (to be added). I'm less concerned at the moment about which facets are used than there is some level of faceted browsing possible. The sheer numbers are going to kill people trying to find something in an alpha list 10,000 entries long.

**Comment by Lomilar** [comment]
Of course, but isn't the first line of defense against overwhelming results search? (both ctrl+f find, and the top bar search)

**Comment by stuartasutton** [comment]
Somewhat. But search assumes some knowledge of the language used the title of what you are looking for. Also, I may only know that what I'm looking for is a framework provided by a specific org, etc.

**Comment by Lomilar** [comment]
So, this is less on the search side and more on the discovery side.

I don't disagree at all, but I'm not sure that starting with the competency viewer is the place for this kind of use case. It is already possible to configure the cass-editor to apply an additional search criterion to limit its search results, so that it can be embedded in things like an organization's detail page.

These filters can be applied to any data field, so filter=schema\:creator:49640492-9040-4478-a2c8-5c888f549fd5 can be used to find frameworks by that creator, as seen here:

https://cassproject.github.io/cass-editor/?ceasnDataFields=true&filter=schema\:creator:49640492-9040-4478-a2c8-5c888f549fd5&server=https://cass.credentialengine.org/api/

This would allow the frameworks for DePaul to appear (and be explorable) in a popup, for instance.

**Comment by Lomilar** [comment]
@stuartasutton This is a candidate for closing if the discussion has gotten to where it needs to be.

Anything outstanding?

**Comment by stuartasutton** [comment]
@Lomilar, I'd prefer to not close this issue until the competency and concept application search/browse has gotten to where it needs to be and not just the discussion. This needs input from @jkitchensSIUC, @siuc-nate before closing. The distinction between search and browse is legitimate; but, currently neither are particularly useful. A purely alpha browse is not so useful now and clearly won't be at scale (even to find one's place in the index. Search has to support more than title terms  or 'known-item' searches.

**Comment by siuc-nate** [comment]
Most of the use cases we've run into are either:
1. How to find x entity by Y competency
2. How to find x competency by Y owner/publisher

The first requires direct interaction with other systems, namely the Registry, since CASS doesn't contain all of the other "x entity" data.

From CASS's perspective, I suspect the second item is more doable. @Lomilar's comment above seems to take care of that (though perhaps there would be some utility in providing an interface that lets users see/search a list of owners and then see the competencies for whichever one they select?).

**Comment by stuartasutton** [comment]
In your examples, Nate, "Y" is known (what information retrieval folks call "known-item" searching).  My concern is finding things where there is no known item and they are searching for words they think would be in such a competency or the label of a concept ("cybernetic").

**Comment by siuc-nate** [comment]
So you're referring to browsing in some structured way, rather than searching, right?

**Comment by stuartasutton** [comment]
Both. Searching names alone is inadequate and browsing an alpha-list of thousands of competency and concept frameworks is inadequate. I get search filters etc.; but how is this enabled with someone just landing on the TOC to make any sense of it beyond known-item searching on title.

**Comment by siuc-nate** [comment]
Do you have an example of something that works in the way you describe? It may be that we're thinking of the same functionality with a different vocabulary.

**Comment by stuartasutton** [comment]
We've talked about one--option to filter by provider
Another by keywords/phrases in the competency or concept definition (i.d. beyond name/title).
Being able to specific initial letters in an alpha-list
Faceted search/filter (browse to useful results)
etc. etc.

These are going to be massive TOCs of stuff.

**Comment by Lomilar** [comment]
Autosuggest of complex search queries based on simple ones is a method I've seen.

ex: DePaul suggest-expanding to author:"DePaul University" (while the search criteria expands with author:`<DePaul URL>`)

**Comment by Lomilar** [comment]
Pending #141

**Comment by Lomilar** [comment]
Remaining discussion to occur regarding known object search (which reaches across the internet in this case) to happen in https://github.com/cassproject/CASS/issues/124.

Please reopen if additional issues remain not covered by #481
