### ISSUE TITLE
Concept Copy (don't link) from other schemes

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#572]
#506

**Comment by Lomilar** [comment]
Probably not a good idea here. Concept schemes use a "two object" model (ask me about it if need be), meaning relations between concepts are part of each concept. This prevents them from being shared between concept schemes, so linking is not an intended capability for concept schemes.

**Comment by stuartasutton** [comment]
This issue seems a bit old but I am assuming it is still active. This has nothing to do with "two object" models. See https://www.w3.org/TR/2009/NOTE-skos-primer-20090818/#secextension and look at the two concept scheme cats example. So, there is no technical barrier in concept schemes to referencing (linking to) a concept in a different scheme.  (Same can be said for Competency Frameworks). 

My problem is, even thought it is doable, should it be done willy-nilly.  My answer is "no" and that each case needs to be looked at carefully and the context of the node in both need to be considered.

**Comment by woodkri** [comment]
Closing as won't do.
