### ISSUE TITLE
Test: What happens when someone enters no name and/or no description

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#60]

**Comment by eddavies** [comment]
![empty gray](https://user-images.githubusercontent.com/23706850/33460609-d190cf76-d5e3-11e7-959d-ddfbd878ec8a.PNG)
Got a grey line for a competency with no name.
![grey with des](https://user-images.githubusercontent.com/23706850/33460649-f22a3a92-d5e3-11e7-826a-dad15e8d9559.PNG)
What happens when it's given a description.

**Comment by eddavies** [comment]
Framework cannot be made with no name.

**Comment by eddavies** [comment]
![get rid of hi](https://user-images.githubusercontent.com/23706850/33460711-4c790da2-d5e4-11e7-95b5-7e5a0fcc897f.PNG)
What happens after adding a competency underneath it, with no name or description.

**Comment by miledivovic** [comment]
Fixed in 4cc8376. Should be prevented from creating competencies with no name.

**Comment by eddavies** [comment]
fix verified
