### ISSUE TITLE
Framework deletion showing an error

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#604]
The error below appears every time I delete one of my test frameworks on ctitest. The framework seems to be actually deleting though.

![error deleting framework](https://user-images.githubusercontent.com/23706850/63534092-2b8f7700-c4c3-11e9-8d63-c5b03e91ac2e.PNG)

**Comment by cwd-mparsons** [comment]
@eddavies We had a check: if the framework name equals: "New Framework", then don't save in the publisher. This was done so that temp/play frameworks were not recorded, until the name changed to a more likely name. 
The step to do the deletes checks if the framework exists. If it doesn't then it returns with a message indicating the framework was not found. The format of the returned class was incorrect, so the message ended up blank. 
This has been corrected, and returns message: NOTE - the framework was not found in the publisher.

**Comment by eddavies** [comment]
I was unaware of this behavior, thank you for the clarification.
