### ISSUE TITLE
Unable to import the O*Net technology skills framework into production

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#630]
I have tried many times to import the O*Net technology skills framework into production. 
The import never finishes. Fritz had noted that the import appears to complete internally but no data is written. 
I have tried importing for the DOL organization, and for credential engine - both fail. 
The latest attempt shows a list of relation urls that I had not seen before. May or may not significant. The image shows there are 3.5mb of additional urls are available - perhaps shows something is happening!

![image](https://user-images.githubusercontent.com/26332112/69196514-5904b480-0af4-11ea-8cdc-0d3be268f90d.png)

**Comment by cwd-mparsons** [comment]
Eventually an error message was displayed:
![image](https://user-images.githubusercontent.com/26332112/69208473-4781d380-0b19-11ea-8adb-b4680ee5d62d.png)

**Comment by Lomilar** [comment]
The technology skills framework imported successfully to Production, but the import request looks like it timed out. It was there when I checked last.

That huge list of updated URLs (it is framework, competencies, and relations) is indeed a sign that the import succeeded, as the server then sent out the list of things that changed.

![image](https://user-images.githubusercontent.com/337692/69263008-54361400-0b79-11ea-8cd2-e802a1e9489c.png)

These timeouts and whatnot continue to be a set of performance and scale issues. The next stage of performance improvements is in this issue here:
https://github.com/Eduworks/ec/issues/68

We should continue to look at why the DoL account isn't able to import.

**Comment by cwd-mparsons** [comment]
Status
19-11-18 
I was able to publish the framework on staging
19-11-20
Production - failed.
I kept running into strange errors while trying to publish the O*Net technology skills, including multiple of: ERR_HTTP2_PROTOCOL_ERROR
I even tried to republish the staging version, which worked Monday – failed as above. 
There was some suggestion that the protocol error could be related to a google update. I tried the publish using Firefox and got the same error.

**Comment by jeannekitchens** [comment]
@cwd-mparsons @woodkri Is this still open?

**Comment by woodkri** [comment]
Yes, we still need to investigate why the DoL account is unable to import this framework.

**Comment by Lomilar** [comment]
@mparsons-ce Give this another shot. We did a reimport of all the O*NET frameworks and https://cass.credentialengine.org/api/ceasn/5b3e205efac3276dd7edfdd1345d8530 works in a fairly reasonable amount of time.

**Comment by mparsons-ce** [comment]
I tried to publish and got the following error:
![image](https://user-images.githubusercontent.com/58825866/75076084-d6a9d900-54c4-11ea-9a6a-c40eb650e085.png)

Publisher is supposed to be a **list** and is being exported as an object:
![image](https://user-images.githubusercontent.com/58825866/75076139-ffca6980-54c4-11ea-98f8-10fd99316c46.png)

**Comment by woodkri** [comment]
I think publisher and creator used to be part of your context and were removed, affecting our translations. I've updated the translation so the "@id" part goes away. You may need to restart Tomcat to see the changes. @mparsons-ce

**Comment by siuc-nate** [comment]
Weird. I updated the site the other day, but not with any changes that should have affected the context, especially like that.  I'll see if I can figure out what happened.

**Comment by siuc-nate** [comment]
Okay, this should be fixed now.  Turns out it was due to a change that was made several weeks ago but wasn't actually part of the live site until the other day.  It had to do with the way stuff borrowed from other schemas is handled when generating the context (the publisher and creator properties both reference ceterms organizations).

**Comment by mparsons-ce** [comment]
Success!
I was able to publish the framework:
https://credentialengineregistry.org/resources/ce-9fab4187-d8e7-11e9-8250-782bcb5df6ac
