### ISSUE TITLE
Importing competencies without proper @ids only half-works

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#652]
Upon trying to import data that looks like this:
![image](https://user-images.githubusercontent.com/21346519/80412950-3e4d1d80-8894-11ea-849b-744b905907eb.png)

I get a result that looks like this:
![image](https://user-images.githubusercontent.com/21346519/80412974-4a38df80-8894-11ea-9412-f91a1a0caa14.png)

The framework is created correctly and CaSS recognizes that there are a number of competencies, which are apparently saved somewhere, but it fails to attach them to the framework.

**Comment by woodkri** [comment]
CaSS only supports non-numeric ids. The framework imports okay since it's a letter, but the competencies are only numbers, so they won't import correctly.

You may run into other issues with something like "A" as the Canonical id though; we handle this with the CaSS-formatted imports by tacking it on the end of the selected server, so you would get something like https://dev.cassproject.org/api/A. I don't think you will want that kind of solution for the CTDL-ASN imports though.

**Comment by siuc-nate** [comment]
I was hoping CaSS would recognize the connections and join the data together after generating the CTIDs and IDs. Instead I had to generate the CTIDs and IDs myself - doable, but not a great user experience.
