### ISSUE TITLE
Toggle to turn show=mine on and off

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#654]

**Comment by jeannekitchens** [comment]
@woodkri @Lomilar we had meetings in the past about users needing to be able to align competencies in their framework to competencies in other frameworks.  We had multiple discussions in the past about this, tested it, did alignments etc.. Of course, users cannot edit another framework.  They need to be able to see only published frameworks in order to align their competencies to others.  I thought this was already enabled.  It seems like this should be a non issue.  Also, by published, we're always saying that in respect to published to the Registry.  Anything that is saved but not approved and published is not complete and therefore cannot be accessed.  What's the timeline to ensure this is enabled?  BTW...I hope this is the correct issue.  @mparsons-ce indicated this issue was setup for what I described but there's no description to ensure we all know what the issue is etc..

**Comment by woodkri** [comment]
I was planning to start work on this toggle today.

I think what you're describing is a separate thing though, the need to show only frameworks that have been published to the registry. We discussed in our weekly meeting a week or two ago that CE can add the URL parameter 'filter' to the iframe to display only frameworks that have had the "Published" field set by the registry. Is there something else that is needed from us?

**Comment by mparsons-ce** [comment]
@woodkri 
What is the format of the filter? Just: 
filter=Published

**Comment by woodkri** [comment]
?filter=Published:*
That will give you any frameworks that have something in the Published field.

**Comment by mparsons-ce** [comment]
Got it - Thanks

**Comment by mparsons-ce** [comment]
Initial testing on staging looks good:
- logged in as an admin
- opened an lopp and CaSS
- only see published frameworks
- clicked on **show only mine** - all published were mine anyway

Created a new user for Vincennes
- opened a Vincennes lopp and CaSS
- again only see published frameworks
- clicked on show mine - none are shown - expected as the new user is the only use for Vincennes

TODO - find a user for a staging org that has created frameworks
