### ISSUE TITLE
If a description is not entered, the name of the framework is assigned to the description on export.

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#659]
While working on #658 I noticed that the description not entered, yet no error occurred while publishing - the framework description is required. 
I found that on export, if the description is empty, the framework name gets assigned to the description. 
I don't recall if this is supposed to be a 'feature' and could not find any relevant past issues with a decision to provide a default description is one was not provided.

**Comment by woodkri** [comment]
This was done intentionally. Do you want it to throw the error when publishing instead? I can take it out if so.

**Comment by stuartasutton** [comment]
This should likely have a broader discussion. Not having a framework description and using non-descriptive titles are a major problems...and will grow significantly larger.

**Comment by mparsons-ce** [comment]
For now I will add an edit to the API and publisher to reject a publish attempt if the description is the same as the framework name.

**Comment by stuartasutton** [comment]
This is something that @jeannekitchens and @siuc-nate should chime in on.

**Comment by siuc-nate** [comment]
Agreed, we should require a description instead of reusing the name.

**Comment by stuartasutton** [comment]
There are many competency frameworks without descriptions (or adequately descriptive titles) that are likely the result of not having and such datapoint because that kind of knowing is assumed by the context in which they are presented which may frequently not be a distinct source worth of a name. All that last sentence meant is that they may frequently not have a source description to map the API...meaning they'd need to generate a description where none existed before.

**Comment by mparsons-ce** [comment]
Per CTDL meeting on June 23, 2020 - There is no change required. The current behavior where on export if there is no framework description, the framework name is used.
