### ISSUE TITLE
Expose "Date Created" and "Date Modified" as user-editable fields

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#666]
This would apply to the new (and if possible old) editors, as it is needed functionality currently.

This is to expose the [ceasn:dateCreated](https://credreg.net/ctdlasn/terms/dateCreated) and [ceasn:dateModified](https://credreg.net/ctdlasn/terms/dateModified) properties as user-editable xsd:date and xsd:dateTime (respectively) fields.

This would apply both to Competency Frameworks and Concept Schemes.

**Comment by woodkri** [comment]
We've been setting schema:dateCreated automatically, and translating that to ceasn:dateCreated. Should we change the translation so that the field we're generating translates to ceasn:repositoryDate instead? We also automatically update schema:dateModified/ceasn:dateModified when an object is edited.

**Comment by woodkri** [comment]
For dateCreated: The data will have both schema:dateCreated and ceasn:dateCreated fields. ceasn:dateCreated will be editable and will indicate the date the original resource was created. schema:dateCreated will translate to ceasn:repositoryDate and indicates the date the data in CaSS was created.

For dateModified: The data will have both schema:dateModified and ceasn:dateModified. ceasn:dateModified will be editable and will indicate the date the original resource was last modified. schema:dateModified will NOT translate and indicates the date the data in CaSS was last modified.

**Comment by gloverkari** [comment]
On export, schema:dateCreated will be translated to ceasn:repositoryDate. However, if ceasn:repositoryDate already exists, should it be translated to schema:dateCreated on import? 

Assuming the answer to the above question is 'yes', the chart below lists the new translations of fields in different scenarios. 
This also assumes that ceasn:dateCreated and ceasn:dateModified will never affect schema:dateCreated and schema:dateModified.

**import -> in CaSS -> export**
ceasn:dateCreated -> ceasn:dateCreated -> ceasn:dateCreated
ceasn:dateModified -> ceasn:dateModified -> ceasn:dateModified
ceasn:repositoryDate -> schema:dateCreated -> ceasn:repositoryDate
no ceasn:repositoryDate -> generate schema:dateCreated -> ceasn:repositoryDate
n/a -> generate schema:dateModified -> none

If the answer to the question is 'no', should the new schema:dateCreated overwrite ceasn:repositoryDate (if it exists)?
ceasn:repositoryDate -> ceasn:repositoryDate -> overwritten by schema:dateCreated
n/a -> generate schema:dateCreated -> ceasn:repositoryDate
no ceasn:repositoryDate -> generate schema:dateCreated -> ceasn:repositoryDate

**Comment by jeannekitchens** [comment]
@gloverkari the dateCreated should be the data the competency framework was created.  That occurs prior to publishing to the Registry.  The respositoryDate should not use this date.  The respositoryDate is the date it was published to the Registry.  

- The dateCreated is provided by the publisher and should not be used for anything other than the date provided by the publisher using the https://credreg.net/ctdlasn/terms#dateCreated property.  This is not generated by CaSS.  
- The dateModified is provided by the publisher and should not be used for anything other than the date provided by the publisher using the https://credreg.net/ctdlasn/terms#dateModified.  This is not generated by CaSS.
- The ceasn:repositoryDate could be generated by using the date the competency framework was published to the Credential Registry.  CaSS wouldn't know this status until it's published though so not sure how CaSS could create this date.
- The date that a competency framework gets published to the Registry needs to be used with the envelope and that should already be happening. Here's an envelope https://credentialengineregistry.org/envelopes/ce-6fdd56d3-0214-4a67-b0c4-bb4c16ce9a13, go the bottom to see dates.

**Comment by sedula27** [comment]
@gloverkari 
The date created and date modified showed in the Cass interface, are they the dates when the the framework is entered into Cass and modified in Cass?
![image](https://user-images.githubusercontent.com/93455942/203122289-007dc912-26fb-4cee-9d9a-234aaa0643be.png)

**Comment by jeannekitchens** [comment]
@gloverkari we established that CaSS needs to display the dates that it already does in the UI to indicate it's been created and modified in CaSS. Your mockup is just fine.  This issue needs to be completed so people can add a date created that has nothing to do with the CaSS date.  The date created most often occurs before anything is enter into CaSS.  in Sandbox it still doesn't allow getting pated the date without entering a time.  Nobody is going to have a time.  We've established this is multiple conversations.  This issue going back to 2020 needs to be closed in early January.  See the screenshot below.  First, I tried to add only a year then a month and a year.  BTW...a month and a year is a real use case. Then I added the day.  Still does not save. 
![image](https://user-images.githubusercontent.com/20917206/211124646-2c4abd06-baeb-43a3-9fa5-6d53304da52f.png)

**Comment by jeannekitchens** [comment]
@gloverkari still issues with this:

1. On sandbox select Date Created and enter mm/dd/yyyy.  Notice the time doesn't show....which is great. but you had indicated you had to include time. ![image](https://user-images.githubusercontent.com/20917206/213940984-18b82a6b-1de1-4739-a26e-a80ee45d8d63.png)
2. The export to ctdl json ld shows 
![image](https://user-images.githubusercontent.com/20917206/213941102-dc938327-fdaa-4d02-a501-ef91c25bd42d.png)
3. I select to add the Date Modified the UI for this is different from Date Created.  It shous mm/dd/yy --:-- --.
![image](https://user-images.githubusercontent.com/20917206/213941165-33947d03-2060-4b12-92de-3ddff3900a98.png)
4. I try to save the Date Modified without a time and get an error message, Value is required to save.
![image](https://user-images.githubusercontent.com/20917206/213941198-bb5ac00b-1044-469d-8c54-608945500b22.png)
5. As we had talked about, people aren't going to have a time so it's not going to make any sense to people to be required to enter a time.  I try to make the time 00:00 but it defaults to 12:00 and then I have to enter either AM or PM.   Otherwise I keep getting the Value is required to save error message.  Even after completing the date and time , I still get the error message, Value is required to save. 
![image](https://user-images.githubusercontent.com/20917206/213941292-c231420b-d997-4d9a-954c-56eedf16f15d.png)

However, if I cancel adding that property and then reselect Date Modified and fill in the complete date and time with PM the first time, it saves .
![image](https://user-images.githubusercontent.com/20917206/213941390-ee7683a9-32e9-41cd-9d3b-24dbdb61095d.png)

The export of the same framework with both the above Date Created and Date Modified shows "2023-01-01T12:00".  If the time is going to be included, shouldn't the AM or PM be included? @mparsons-ce is the time included with dates entered by users for any other classes?  
![image](https://user-images.githubusercontent.com/20917206/213941495-708b5339-8285-4fd9-aef8-18a9f5fb06ae.png)

**Comment by mparsons-ce** [comment]
@jeannekitchens Created dates (including dateEffective) are all date properties (not datetime). 
There is a startTime property but it is not used anywhere at this time. 
The ctdlasn properties of ceasn:dateValidFrom/To are datetime unlike the seemingly related ceterms:dateEffective and expirationDate
The API ignores any time component of a property that is defined as a date.

**Comment by gloverkari** [comment]
I left the dateModified as dateTime based on the CaSS/CTDL ASN Mapping range. However, I noticed new columns have been added  showing the format and an example (very helpful - thanks!). The format shown has no time for dateModified. I'll update dateModified to a date only type then.
