### ISSUE TITLE
SOC codes not being retained on import

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#824]
Today we tried importing the [RSD Cybersecurity collection](https://docs.google.com/spreadsheets/d/1V_KQqdL4K8QUSOsboDj4Z2HASuTKW-JdM28HvU-NXfg/edit#gid=501611954).  We were able to import the framework, but the SOC codes were not translated to meaningful data nor were they included at all in the export.  It seems like they were not imported properly/at all.

Export link:
https://dev.cassproject.org/api/ceasn/369952bf505a99fabdda57119e007f68

Note: At the time of the import, the column for the data was just "socList" not "ceasn:socList" (as the latter is not a CTDL-ASN property).

**Comment by woodkri** [comment]
You're right, these did not import. I'm just realizing that the old dev repository that sandbox is on has not been updated to the latest version of CaSS. My apologies! This is up on staging but not sandbox yet.

@Lomilar Can you update dev.cassproject.org? If you usually just use the install script, let me know and I can do it.

**Comment by woodkri** [comment]
Looking more closely at the data here, I don't think you had permission to overwrite the competencies so I think that's why the other fields did not show up in the imported competencies. It appears that these competencies were originally imported under a different user account than the one used to import the framework. In addition, because of the permissioning/template issue I mentioned the other day on sandbox and staging, the admin account can't edit these.

I could probably delete the framework and competencies using the ppk from production, and a reimport after that would at least give the framework and competencies the same ownership, though they still wouldn't have the correct admin key.

**Comment by siuc-nate** [comment]
For future reference/documentation purposes, is the SOC list header case sensitive? I was able to successfully upload with `socList` but I'm wondering if `SOCList` would have also worked.

**Comment by woodkri** [comment]
Great! Yes, it's case sensitive so would need to be socList. Same with cipList and naicsList.
