### ISSUE TITLE
New concept scheme editor duplicates source and creator upon edit

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#830]
I noticed that whenever I edit a concept scheme in the new concept scheme editor, the creator and source show duplicates .
Below shows the old and new editor, where the old editor shows a single value, and the new editor shows duplicates:

![image](https://user-images.githubusercontent.com/58825866/116292249-1b7d6f80-a75b-11eb-8e67-7a8d87e1e649.png)

**Comment by woodkri** [comment]
This looks like a data issue with that concept scheme (and maybe some others). If I pull up a CaSS export of Learning Method in production, it has both dc:source and http://purl.org/dc/elements/1.1/source as fields on the concept scheme. If I go to a similar scheme, Action Status, it only has dc:source and only shows the one source value in the interface. Same thing with creator. The new editor uses expanded json-ld fields while the old one did not, so that's why the duplicate field is showing up in one interface and not the other.

I can write up a script to remove the extra fields if you'd like, just let me know.

**Comment by mparsons-ce** [comment]
@woodkri Sorry for the delay. Yes, please remove the extra fields.
Thanks

**Comment by woodkri** [comment]
The duplicate fields have been removed.
