### ISSUE TITLE
Production: After user creates a framework, it no longer shows in CaSS, and can't publish it. 

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#850]
Tracey Kelly of Software Engineering Institute created a new framework, and approved it.
- Certified Computer Security Incident Handler Competency Areas
- frameworkctid=ce-44409cba-15b2-4f25-859f-c1de8d5ac691
Scarlett tried to publish it and was unable to. She then tried to edit it and just gets the spinner.

I tried logging in as Tracey, and went to CaSS. No frameworks are shown, only a list of orphan competencies.
![image](https://user-images.githubusercontent.com/58825866/117859339-77b0bb00-b254-11eb-9f52-314db0d28b95.png)

**Comment by jeannekitchens** [comment]
@woodkri it is on production.

**Comment by jeannekitchens** [comment]
@woodkri are you saying the framework was deleted but the competencies were left as orphans?  There's definitely an issue if users can unwittingly create orphans.  Also, they had approved it to be published. so the delete would have occured after the approval but the delete didn't change the approval to be published status so we have some other issues.

**Comment by woodkri** [comment]
I can't say if the orphan competencies came from that operation or not. All I can see in the logs is that the framework was deleted along with several relations and competencies.

We can look into it and try to reproduce, though I'm not sure which version of the editor this was using.

**Comment by jeannekitchens** [comment]
@woodkri we need to understand the user actions that cause orphans.  There shouldn't be any orphans caused by deleting a framework.  We can see from our logging that the framework was deleted.  I'll reach out to the user but doubt they'll really know what caused the orphans.  Also, to create competencies, you first have to create a framework.  How is it possible to create competencies without a framework.  There's not interface to create just competencies.  Once orphans are created there appears to be no way to delete them.  The user has to be able to delete them.  I'm logged in as the user.  I have edit rights as the user.  I see the orphans as shown below.  Selecting any of them shows the msessage below.  How do we and users delete them?  
![image](https://user-images.githubusercontent.com/20917206/117911950-79e63a00-b293-11eb-8a8f-6aeccfa179cf.png)
![image](https://user-images.githubusercontent.com/20917206/117912035-9c785300-b293-11eb-9b96-630981e49a18.png)

**Comment by woodkri** [comment]
I've created a ticket to enable deleting orphans from the interface.

Like I said, we can try to reproduce deleting a framework and leaving orphan competencies behind. I have an open ticket to add a bulk delete method to CaSS which I suspect might help here.

I've also seen orphans created when re-importing a framework that has a different set of competencies than the original framework did. They can be created if a user clicks to remove a competency from a framework but not delete as well.

**Comment by mparsons-ce** [comment]
Test:
- Login as Tracey Kelly
- created a framework and then logged out
- logged back in and was able to see and edit the framework
- logged in as me, and was able to see and edit the framework

Approved as fixed
