### ISSUE TITLE
Add ListId to concepts in concept editor.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#91]

**Comment by Lomilar** [comment]
Part of #65

**Comment by Lomilar** [comment]
This is not a numeric index. This is a location in a tree based on an arbitrary notation.

**Comment by Lomilar** [comment]
Done by #109

**Comment by eddavies** [comment]
"Competencies with lower alphanumeric values for this property come before competencies with higher values."
Using ASCII makes it so lowercased concepts or frameworks are at the bottom of the list.

**Comment by eddavies** [comment]
Do we need this issue open? There is a listid and it works. The ordering is related to issue #57

**Comment by Lomilar** [comment]
This conflicts with #65 as well.

@stuartasutton Should we sort based on ListID or based on drag/drop ordering?

**Comment by stuartasutton** [comment]
The `listId` values are recorded by the person or process that enters the data and are only included if the creator of the framework specifies. The `listId` property identifies the sequence order of an array of sibling concepts **as expressed by the creator of the framework**. If the original framework does not express any order of sibling nodes at a particular level of the framework, then that array of siblings is functionally unordered and has **no** `listId` value. So, unordered bulleted lists in the source (e.g., "•") have no `listID` and are functionally unordered. 

The `listIds` for an array of sibling competencies alphanumerical. In repositories with competency frameworks in the thousands, I've never encountered anything but alphanumeric numbers. Since they are arrays of siblings, there are none that mix numbers and upper- or lower-case letters. No accompanying punctuation is included--"1" and not "1."

Here's an example that has simple numeric `listId` values designated for two levels--Domain and Knowledge/Skill:

<img width="866" alt="screenshot 2018-03-02 12 53 59" src="https://user-images.githubusercontent.com/2939046/36921404-1f7d6a32-1e19-11e8-9ce7-ad6c0dcb8f21.png">

**Comment by Lomilar** [comment]
https://cassproject.github.io/cass-editor/index.html?ceasnDataFields=true&frameworkId=https://dev.cassproject.org/api/data/schema.cassproject.org.0.3.Framework/5424546a-bf03-478d-994a-1e89f58baeb9/1520027876174

Now sorting by listID if available. 1.a.1 comes before 1.a.2 comes before 1.a.10.

**Comment by stuartasutton** [comment]
No, that is not correct. It's never something like "1.a.1". Something like that is in `codedNotation`. The `listId` handles simple numbers and letters that the creator uses simply denote position in an array/list

**Comment by Lomilar** [comment]
Simple listIds (1,2,3,4,5) work as well. We just put in the extra work to sort by the natural order in a number of scenarios.

Is it required that this field be just alphanumeric ([a-z][0-9])+ (with no punctuation)?

**Comment by stuartasutton** [comment]
ASN has it as a literal.

**Comment by Lomilar** [comment]
RDF Literals can be strings, urls, or <insert langstring special case>.

If we're not prohibiting things, we should be okay. a,A,b,B is also how letters are sorted, so we aren't suffering from ASCII table sort weirdness. OK to close?

**Comment by stuartasutton** [comment]
I think it is OK to close.
